### ISSUE TITLE
Support for json schema: "not" 

### ISSUE THREAD

**Issue by swamikevala** [cloudflare/json-schema-docs-generator#13]
Sometimes I would like to specify my links schema in the following form 

```
"contact": {
   "allOf": {
       "$ref": "#",
       "not": {
           "required": ["unwanted1", "unwanted2"]
        }
    }
}
```

Especially when I have a large number of properties on my base object, but for this particular API call some of them don't make sense in this context.

Currently, the example does not get generated if I use this structure

**Comment by tajo** [comment]
We don't provide any support for `not` right now. I think it doesn't make much sense since this library is not a schema validator and `not` seems to be useful [just for that](https://spacetelescope.github.io/understanding-json-schema/reference/combining.html#not). I am not sure if your use case is valid. What happens if both

```
"not": {
  "required": ["unwanted1", "unwanted2"]
}
```

and 

```
"required": ["unwanted1", "unwanted2"]
```

appears in the same schema (allOf) ?

**Comment by handrews** [comment]
@swamikevala we have replaced this project with a new system called Doca, and I have migrated this feature request over there as cloudflare/doca#18.
