### ISSUE TITLE
Missing helper: "lowercase"

### ISSUE THREAD

**Issue by sabakugaara** [cloudflare/json-schema-docs-generator#15]
when I run the ecommerce  example, an error occurred:
```
Missing helper: "lowercase"
```

I fixed it by edit  `examples/ecommerce/bin.js`:
```
var Handlebars = require('handlebars');
Handlebars.registerHelper('lowercase', function(value) {
    if (value) {
        return new Handlebars.SafeString(value.toLowerCase());
    } else {
        return '';
    }
});
```

Is this a question?

**Comment by bojand** [comment]
Same here. It's because of this:
```
<strong>{{lowercase @key}}</strong><br />
```

**Comment by akenn** [comment]
@sabakugaara Yep that's an issue. Would adding the fix above to `drivers/template.js`? I want to include it there instead of `examples/ecommerce/bin.js` because the bootstrap theme can be used for more than just the example.

Also would it make sense to have a `helpers/` folder inside of the `drivers/` folder for handlebars helpers like this, or just keep them inside `drivers/template.js`? cc @toekneestuck @thejameskyle

**Comment by toekneestuck** [comment]
I didn't update any of the themes or examples when rewriting this for 1.0, sorry about that. I think the lowercase helper/use should be removed from the template all together. Transformations to template data should be done in a transformer, which the Composer applies before sending the data to the template driver

**Comment by sabakugaara** [comment]
LGTM :) , About when 1.0 version will be resleased?

**Comment by toekneestuck** [comment]
I've already released 1.0 (and a few bug fixes). I just failed to go back through and clean up the examples/themes.

**Comment by sabakugaara** [comment]
Thanks!

**Comment by tajo** [comment]
The fix is here: https://github.com/cloudflare/json-schema-docs-generator/pull/29
